### ISSUE TITLE
waf build error: ‘zmq::recv_flags’ has not been declared

### ISSUE THREAD

**Issue by bbalaji-ucsd** [tkn-tub/ns3-gym#33]
I hit the following error when I tried to install as per instructions in Readme. 

```
../src/opengym/model/opengym_interface.cc: In member function ‘void ns3::OpenGymInterface::Init()’:
../src/opengym/model/opengym_interface.cc:192:36: error: ‘zmq::send_flags’ has not been declared
   m_zmq_socket.send (request, zmq::send_flags::none);
                                    ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc:197:41: error: ‘zmq::recv_flags’ has not been declared
   (void) m_zmq_socket.recv (reply, zmq::recv_flags::none);
                                         ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc: In member function ‘void ns3::OpenGymInterface::NotifyCurrentState()’:
../src/opengym/model/opengym_interface.cc:259:36: error: ‘zmq::send_flags’ has not been declared
   m_zmq_socket.send (request, zmq::send_flags::none);
                                    ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc:264:41: error: ‘zmq::recv_flags’ has not been declared
   (void) m_zmq_socket.recv (reply, zmq::recv_flags::none);
                                         ^~~~~~~~~~
```

**Comment by pgawlowicz** [comment]
can you check which zmq version do you have installed?
probably you will need to update it

**Comment by bbalaji-ucsd** [comment]
Current libzmq version is 4.3.2
Current  pyzmq version is 19.0.1

Seems to be the latest version?

**Comment by Forsworns** [comment]
> Current libzmq version is 4.3.2
> Current  pyzmq version is 19.0.1
> Seems to be the latest version?

I encountered a similar problem as you, see the 32nd [issue](https://github.com/tkn-tub/ns3-gym/issues/32).

How do you installed the libzmq5-dev? I cannot find this package on Ubuntu16.04... I used `sudo apt-get install libzmq5-dev` and only got libzmq3-dev. For me, I think maybe the problem comes from the libzmq3-dev.

**Comment by pgawlowicz** [comment]
Can you revert the last commit, where I applied a pull request to replace deprecated functions of zmq and check?
Probably I will need to handle zmq versions in some way.

**Comment by Forsworns** [comment]
Yep, I have reverted that commit and checked. That commit is right. The `send` and `recv ` functions need a flag parameter now:) 
But it seems that the definition of the  `zmq::recv_flags` is not included in our header. I test it this morning, later I'll post the record.

**Comment by bbalaji-ucsd** [comment]
Thank you! That error was resolved.

I ran into a protobuf version error now. Which version of protobuf should I be using?
```
../src/opengym/model/opengym_interface.cc:258:69: error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]
   envStateMsg.SerializeToArray(request.data(), envStateMsg.ByteSize());
                                                                     ^
In file included from /usr/local/include/google/protobuf/generated_enum_util.h:36:0,
                 from /usr/local/include/google/protobuf/map.h:49,
                 from /usr/local/include/google/protobuf/generated_message_table_driven.h:34,
                 from ../src/opengym/model/messages.pb.h:26,
                 from ../src/opengym/model/container.h:27,
                 from ../src/opengym/model/opengym_interface.cc:29:
/usr/local/include/google/protobuf/message_lite.h:408:7: note: declared here
   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
       ^~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by bbalaji-ucsd** [comment]
Oh never mind the above. I saw the correct version is 3.6.1 from readme. It works now with the previous commit, thank you!

**Comment by zlh004** [comment]
I met the same mistake and didn't solve it.
How can I solve it?
thanks a lot

**Comment by HyungjunJu** [comment]
I'm suffering the same issue as you. Can you explain how the solved zmq version issue?

**Comment by HyungjunJu** [comment]
> I'm suffering the same issue as you. Can you explain how the solved zmq version issue?

I found that using the newest version of zmq (4.2.5) will occur the error. So I did downgrade the zmq(4.1.4) and it works now.

**Comment by mostafa-shaheen** [comment]
> > I'm suffering the same issue as you. Can you explain how the solved zmq version issue?
> 
> I found that using the newest version of zmq (4.2.5) will occur the error. So I did downgrade the zmq(4.1.4) and it works now.

How did you downgrade to zmq 4.1.4 ?

**Comment by HyungjunJu** [comment]
Hello Mostafa Shahin,

I removed zmq manually, likewise sudo apt remove zmq.
and download specific version of zmq in below site.
 https://github.com/zeromq/zeromq4-1/releases
Install libzmq 4.1.4 by source codes.
e.g.) tar xvf zeromq-4.1.4.tar.gz
cd zeromq-4.1.4/
sudo ./configure
sudo make install



2020년 10월 10일 (토) 오후 8:57, Mostafa Shahin <notifications@github.com>님이 작성:

**Comment by testMondey** [comment]
I build successfully on Ubuntu20.04 with libzmq 4.3.2; but on Ubuntu18.04 with libzmq 4.2.5, it failed, the error is same as the above. why? i didn't find where is zmq::send_flags or zmq::recv_flags.

../src/opengym/model/opengym_interface.cc: In member function ‘void ns3::OpenGymInterface::Init()’:
../src/opengym/model/opengym_interface.cc:192:36: error: ‘zmq::send_flags’ has not been declared
   m_zmq_socket.send (request, zmq::send_flags::none);
                                    ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc:197:41: error: ‘zmq::recv_flags’ has not been declared
   (void) m_zmq_socket.recv (reply, zmq::recv_flags::none);
                                         ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc: In member function ‘void ns3::OpenGymInterface::NotifyCurrentState()’:
../src/opengym/model/opengym_interface.cc:259:36: error: ‘zmq::send_flags’ has not been declared
   m_zmq_socket.send (request, zmq::send_flags::none);
                                    ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc:264:41: error: ‘zmq::recv_flags’ has not been declared
   (void) m_zmq_socket.recv (reply, zmq::recv_flags::none);

**Comment by Zdarling** [comment]
I encountered the same problem. After manually downgrading libzmq to 4.14, the compiler still found an error and indicated that it was missing zmq.hpp File, manual download zmq.hpp File, put into / usr / include, rebuild, and use it successfully

**Comment by testMondey** [comment]
> I encountered the same problem. After manually downgrading libzmq to 4.14, the compiler still found an error and indicated that it was missing zmq.hpp File, manual download zmq.hpp File, put into / usr / include, rebuild, and use it successfully

haha！ I tried libzmq 4.14 but found an error that no zmq.hpp, too. Now I update my ubuntu 18.04 to 20.04 and all is settled. Maybe next time I found a similar error, I will try your method. Thanks!

**Comment by wanghelong666** [comment]
../src/opengym/model/opengym_interface.cc: In member function ‘void ns3::OpenGymInterface::NotifyCurrentState()’:
../src/opengym/model/opengym_interface.cc:259:36: error: ‘zmq::send_flags’ has not been declared
   m_zmq_socket.send (request, zmq::send_flags::none);
                                    ^~~~~~~~~~
../src/opengym/model/opengym_interface.cc:264:41: error: ‘zmq::recv_flags’ has not been declared
   (void) m_zmq_socket.recv (reply, zmq::recv_flags::none);
                                         ^~~~~~~~~~

Waf: Leaving directory `/home/long/ns3-gym/ns3-gym-master/build'
Build failed
 -> task in 'ns3-opengym' failed with exit status 1 (run with -v to display more information)
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
how to solve it?? thank you.

**Comment by LiYufengzz** [comment]
> I encountered the same problem. After manually downgrading libzmq to 4.14, the compiler still found an error and indicated that it was missing zmq.hpp File, manual download zmq.hpp File, put into / usr / include, rebuild, and use it successfully

where did you download zmq.hpp file ? I download and put into /usr/include,but some other errors occurred.It seems that send and recv function have changed with zmq.hpp updating.

error: 'send' is deprecated: from 4.3.1, use send taking message_t and send_flags [-Werror,-Wdeprecated-declarations]
  m_zmq_socket.send (request);
error: 'recv' is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags [-Werror,-Wdeprecated-declarations]
  m_zmq_socket.recv (&reply);

**Comment by wangxn2015** [comment]
Hi, firstly, thank the author for his great contribution. 
Secondly, I encountered the same problem-- "zmq::send_flags has not been declared"  under ubuntu16.04 using libzmq3-dev=4.1.4-7 and libzmq5=4.1.4-7. Hope someone can help.

**Comment by confifu** [comment]
The problem is with libzmq version. Ubuntu 18.04 has older version which causes the error, version 20.04 has more recent version that works. A simple solution is to add 20.04 repos by doing this.
```
sudo apt-add-repository "deb http://in.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse"
sudo apt-add-repository "deb-src http://in.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse"
sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu focal main universe restricted multiverse"
sudo apt-add-repository "deb-src http://archive.ubuntu.com/ubuntu focal restricted universe multiverse main"
sudo apt-get update
```
This will make sure that you will install the version of `libzmq` available in 20.04 (focal fossa)
